
import NavBar from "./components/NavBar";
import SideBar from "./components/SideBar";
import "./globals.css";


import { Box, CssBaseline } from "@mui/material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Box sx={{ display: "flex" }}>
          <CssBaseline />
          <SideBar />
          <Box
            component="main"
            sx={{
              flexGrow: 1,
              bgcolor: "background.default",
              padding: 3,
              marginLeft: 30,
              marginTop: 8,
            }}
          >
            <NavBar />
            { children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
